/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PostPreview: typeof import('./components/PostPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDetail: typeof import('./components/UserDetail.vue')['default']
    UserProfileCard: typeof import('./components/UserProfileCard.vue')['default']
    UserSearch: typeof import('./components/userSearch.vue')['default']
  }
}
